Fix Latex and update media style
eol-uchile/eol-vof-xblock pull request #7
Opened 2024-04-08 20:32 UTC by Lozamded

Se soluciono problemas de compatibilad de latex por medio de la biblioteca mathjax ademas se actualizaron los bullets para las tablas de media

2024-04-15 18:54 UTC, tomaspemora requested changes
Sugiero mover la integración con MathJax a nivel de tema como está implementado [aquí](https://github.com/eol-uchile/eol-uchile-theme-2020/blob/master/lms/templates/dashboard.html#L44). Implementarla a nivel de bloque puede traer problemas de eficiencia y compatibilidad.

2024-04-15 18:59 UTC, tomaspemora requested changes
Los commits 6eba5a83e11c37e89e8f5b89f873fd0b2b23f07f y dd1df96487781cc819ea921e50c7920b6b1a1b90 debiesen ser 1 solo donde se implementa la funcionalidad de identificador único. 

Sugiero revisar la necesidad de añadir este campo, dado que existe el block_id el cuál es un identificador único en toda la plataforma.

2024-04-15 18:59 UTC, tomaspemora commented on vof/public/js/vof.js
Esto no debiese ir en este commit

2024-04-15 18:59 UTC, tomaspemora commented on vof/public/js/mathJax.js
Esto no debiese ir en este commit

2024-04-15 18:59 UTC, tomaspemora commented on vof/vof.py
> -                'public/js/mathJax.js',
Esto no debiese ir en este commit

2024-04-15 21:29 UTC, fsologureng requested changes

2024-04-15 21:29 UTC, fsologureng commented on vof/public/js/vof.js
> +        console.log("Existo soy el vof")
Este mensaje será visto por cada instancia del xblock y junto a cualquier otro mensaje en el navegador.
La función no hace nada más. Sugiero removerla para no agrandar más la normalmente recargada cola de funciones a ejecutar durante el evento load de Page.

2024-04-15 21:29 UTC, fsologureng commented on vof/tests.py
> +        self.assertEqual(self.xblock.id_specific,"1")
No pasa el test.
```
E       AttributeError: 'VoFXBlock' object has no attribute 'id_specific'
```

2024-04-17 20:33 UTC, Lozamded commented
Se realizo un squash con los cambios finales

2024-04-17 21:08 UTC, tomaspemora commented
@Lozamded Hola Diego. Aún vemos algunas modificaciones que no se han aplicado de los comentarios que dejamos en el PR. Solicito por favor aplicarlos antes de subirlos a la plataforma.

2024-04-18 13:32 UTC, fsologureng requested changes

2024-04-18 13:32 UTC, fsologureng commented on vof/public/html/vof.html
> +      <div class="tablagrande" id="VOF_{{id_especifico}}">
Acá queda un par de referencias a una variable que ya no existe.

2024-04-18 13:32 UTC, fsologureng commented on vof/vof.py
> +
Salto de linea extra. Innecesario.

2024-04-18 13:32 UTC, fsologureng commented on vof/vof.py
> +
Salto de linea extra. Innecesario.

2024-04-18 14:40 UTC, Lozamded commented
Hola, aplicadas las sugerencias, ademas de probarse que ese funcionando correctamente en la plataforma de development

2024-04-23 14:05 UTC, tomaspemora requested changes
Aún falta aplicar los cambios sugeridos por @fsologureng en los comentarios del PR.

2024-04-25 19:42 UTC, Lozamded commented
Se arreglaron mas cambios de espacios e indentación , quedo atento a mas posibles modificaciones

2024-04-25 20:00 UTC, fsologureng commented on vof/public/html/vof.html
> +<div class="problem vof_block {{theme}} problems-wrapper" >
Este cambio permanece y es innecesario.

2024-04-25 20:01 UTC, fsologureng commented on vof/vof.py
> +                'show_answers': self.show_answer,
Agregar espacio al final de la linea.

2024-04-25 20:11 UTC, fsologureng commented on vof/public/html/vof.html
> +      <div class="tablagrande" id="VOF_{{id_especifico}}">
Este cambio tampoco está implementado. Si bien no se usa, el ID quedará duplicado si el xblock se usa más de una vez en la página, dejando el HTML inválido.

2024-04-26 18:23 UTC, Lozamded commented
Elimine ahora los espacios mas pequeños que no me habia percatado antes. deberia ahora estar Ok

2024-04-26 18:40 UTC, fsologureng commented
> Elimine ahora los espacios mas pequeños que no me habia percatado antes. deberia ahora estar Ok

Veo todo bien, salvo unas minucias de indentación.
Falta el squash y un mensaje claro para el commit. El mensaje del pr parece útil.

2024-05-06 15:14 UTC, Lozamded commented
Se realizó el squash pertinente y el mensaje

2024-05-06 16:45 UTC, fsologureng approved these changes

2024-05-06 18:34 UTC, tomaspemora approved these changes
También lo veo ok.

2024-05-06 19:16 UTC, merged